# ==============================================================================
# ANSIBLE INVENTORY FILE (EXERCISE 1)
# ==============================================================================
# Ubah alamat IP dan user sesuai dengan mesin VirtualBox / Server target Anda.

[webservers]
web1 ansible_host=192.168.1.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
web2 ansible_host=192.168.1.11 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
